name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1  
    # - name: Configure AWS Credentials for us region audience
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     audience: sts.amazonaws.com.cn
    #     aws-region: us-east-3
    #     role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role


